### ISSUE TITLE
Players are allowed to duplicate unregistered adminonly entities

### ISSUE THREAD

**Issue by thegrb93** [wiremod/advduplicator#65]
Nukes, sky editors, etc.

**Comment by AbigailBuccaneer** [comment]
Somewhat related to #64.

**Comment by thegrb93** [comment]
Should this tool be deprecated by now anyway?

**Comment by AbigailBuccaneer** [comment]
No, it shouldn't. AdvDupe2 is unrelated to it. They have entirely different codebases, with different features and different bugs.

We only took over maintenance of AdvDupe2 because it had been abandoned and it had bugs that were holding back Wiremod improvements. It is in no way a successor to Adv Duplicator. (The awful naming scheme was inherited from the original authors. Frankly, naming their duplicator addon AdvDupe2 was kind of an inconsiderate thing to do, but meh.)

**Comment by thegrb93** [comment]
It does the same thing as advdupe except better so I'd say it's appropriate.

**Comment by Divran** [comment]
>It does the same thing as advdupe except better so I'd say it's appropriate.

The only thing it does better is preserving constraints without sagging. Everything else, adv dupe 1 does better, because adv dupe 2 has so many bugs.

**Comment by thegrb93** [comment]
Not until this bug is fixed ;)

**Comment by Mornedil** [comment]
In the meanwhile you can use URS to restrict entities which are duped.
I was able to successfully restrict edit_sky, edit_fog, and edit_sun.

**Comment by Divran** [comment]
Sorry for the late reply, but 

>Not until this bug is fixed. Also advdupe2 is faster, has area copy, and it doesn't store dupe files on the server.

advdupe2 only pastes things faster because it was coded to do so. Adv dupe 1's code could easily be sped up, but there's no need. Area copy is useless (at least for me) and only makes it easier for non-admins to sneak "virus" E2s into the area of admin's area copies in order to run concmds on them. Storing dupe files on the server is a good backup. Adv dupe 1 supports downloading the files to the client as well, but the UI could use some updating. All that being said, if you prefer advdupe2..
